model:
  large_model:
    name: 'resnet50'
    pretrained: True
  small_model:
    name: 'resnet18'
    pretrained: True

dataset:
  name: 'ImageNet-C'
  path: '/workspaces/COCA_reprod/data/Tiny-ImageNet-C'
  batch_size: 4

optimizer:
  name: 'Adam'
  lr: 0.001

coca:
  lambda_co_adaptation: 1.0
  lambda_self_adaptation: 1.0 